 const data = [
{
  active: "active",
id: 0,
nombre: "Plato Tenca",
descripcion: "Plato de cóctel en madera de Raulí natural, con tres divisiones, acabado con cera natural, compatible con alimentos.",
categoria: "Plato",
material: "Raulí",
dimensiones: "38 x 18 cms. aprox.",
precio: "$25.000",
produccion: "Fabricación 7 días.",
img: "https://storage.googleapis.com/peuco-3530c.appspot.com/productos/IMG_0001.jpg",
orientacion: "vertical",
},{
id: 1,
nombre: "Plato Tórtola",
descripcion: "Plato de cóctel de tres divisiones, perfecto para picoteos y salsa, con acabado de cera natural compatible con alimentos.",
categoria: "Plato",
material: "Raulí",
dimensiones: "45 x 22 cms. aprox.",
precio: "$30.000",
produccion: "Fabricación 7 días.",
img: "https://storage.googleapis.com/peuco-3530c.appspot.com/productos/IMG_9977.jpg",
orientacion: "vertical",
},{
id: 2,
nombre: "Plato Zorzal",
descripcion: "Plato de Raulí para cóctel, con dos divisiones rectangulares, perfecto para salsas y picoteos.",
categoria: "Plato",
material: "Raulí",
dimensiones: "26 x 23 cms. aprox.",
precio: "$20.000",
produccion: "Fabricación 7 días.",
img: "https://storage.googleapis.com/peuco-3530c.appspot.com/productos/IMG_9986.jpg",
orientacion: "vertical",

},{
id: 3,
nombre: "Tabla Chincol",
descripcion: "La más simple de nuestras tablas para asados, fabricada en raulí, sellada con pasta de cera de abejas compatible con alimentos.",
categoria: "Tabla",
material: "Raulí",
dimensiones: "37 x 20 cms. aprox.",
precio: "$15.000",
produccion: "Fabricación 5 días.",
img: "https://drive.google.com/uc?export=view&id=1yvw3o8MqdeKyGNFqNwIekJm3Ad6P3z6y",
orientacion: "horizontal",
},{
 id: 4,
nombre: "Tabla Chercán",
descripcion: "Dale un toque especial a tus asados con esta hermosa tabla con empuñaduras de herradura sellada con pasta de cera.",
categoria: "Tabla",
material: "Raulí",
dimensiones: "40 x 20 cms. aprox.",
precio: "$20.000",
produccion: "Fabricación 5 días.",
img: "https://storage.googleapis.com/peuco-3530c.appspot.com/productos/_MG_0018.jpg",
orientacion: "vertical",
},{
id: 5,
nombre: "Perchero Queltehue",
descripcion: "Perchero de pared en madera de Raulí, de seis ganchos. Incluye tirafondos de 4 pulgadas para su instalación.",
categoria: "Perchero",
material: "Raulí",
dimensiones: "75 x10 cms. aprox.",
precio: "$40.000",
produccion: "Fabricación 10 días.",
img: "https://storage.googleapis.com/peuco-3530c.appspot.com/productos/_MG_0073.jpg",
orientacion: "horizontal",
},{
id: 6,
nombre: "Perchero Pequén",
descripcion: "Pequeño perchero de pared, en madera de Raulí, de tres ganchos, incluye tirafondos de 4 pulgadas para instalación.",
categoria: "Perchero",
material: "Raulí",
dimensiones: "45 x 10 cms. aprox.",
precio: "$25.000",
produccion: "Fabricación 10 días.",
img: "https://storage.googleapis.com/peuco-3530c.appspot.com/productos/_MG_0162.jpg",
orientacion: "horizontal",
}
];


module.exports = data;